{% set version = '0.11.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-adjustedcurves
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/adjustedCurves_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/adjustedCurves/adjustedCurves_{{ version }}.tar.gz
  sha256: d093a353d892d9aa1c07c0b9654337fa11467eb61a4fa8cdb28ed198a24bf910

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-doparallel
    - r-dorng
    - r-dplyr >=1.0.0
    - r-foreach
    - r-rlang
    - r-survival >=3.0.0
  run:
    - r-base
    - r-r.utils
    - r-doparallel
    - r-dorng
    - r-dplyr >=1.0.0
    - r-foreach
    - r-rlang
    - r-survival >=3.0.0

test:
  commands:
    - $R -e "library('adjustedCurves')"           # [not win]
    - "\"%R%\" -e \"library('adjustedCurves')\""  # [win]

about:
  home: https://robindenz1.github.io/adjustedCurves/
  dev_url: https://github.com/RobinDenz1/adjustedCurves
  license: GPL-3.0-or-later
  summary: Estimate and plot confounder-adjusted survival curves using either 'Direct Adjustment',
    'Direct Adjustment with Pseudo-Values', various forms of 'Inverse Probability of
    Treatment Weighting', two forms of 'Augmented Inverse Probability of Treatment Weighting',
    'Empirical Likelihood Estimation' or 'Targeted Maximum Likelihood Estimation'. Also
    includes a significance test for the difference between two adjusted survival curves
    and the calculation of adjusted restricted mean survival times.  Additionally enables
    the user to estimate and plot cause-specific confounder-adjusted cumulative incidence
    functions in the competing risks setting using the same methods (with some exceptions).
    For details, see Denz et. al (2023) <doi:10.1002/sim.9681>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - isuruf
